import {
  API_URL,
  COOKIE_PREFIX,
  CSRF_TOKEN_COOKIE_NAME,
  JWT_COOKIE_NAME,
  updateApiUrl,
  updatePanoWebsiteUrl
} from "$lib/variables.js";
import { getCredentialsServerSide } from "$lib/services/auth.js";
import { internalLibsHash } from "$lib/internalLibs.js";
import { runtimeShimsHash } from "$lib/runtimeShims.js";

function stripModulePreload(linkHeader) {
  const parts = linkHeader
    .split(",")
    .map((p) => p.trim())
    .filter(Boolean);

  const kept = parts.filter((p) => !/;\s*rel="?modulepreload"?/i.test(p));

  return kept.length ? kept.join(", ") : null;
}

function getCookieWithHttpFallback(cookies, baseName) {
  return cookies.get(baseName) ?? cookies.get(`${baseName}_http`);
}

/** In production, skip logging common client/bot noise (wrong method, stray POST to non-action routes). */
function shouldSuppressServerErrorLog(error) {
  if (process.env.NODE_ENV !== "production") return false;
  if (error?.status === 405) return true;
  const msg = String(error?.message ?? "");
  if (msg.includes("No form actions exist")) return true;
  return false;
}
// Plugins' bare specifiers resolve to the tiny STABLE shim modules generated by
// scripts/generate-runtime-shims.js. Each shim re-exports the HOST bundle's own live
// module instance from the registry populated by src/hooks.client.js, so host pages
// and plugins share one Svelte runtime and no second runtime copy is downloaded at
// hydration. The shim URLs never change across deploys (stale cached HTML keeps
// working); their CONTENT only changes when the svelte/sdk dependency is upgraded,
// which the ?v=<runtimeShimsHash> query cache-busts — safe here, unlike the old
// /lib?v= scheme, because a shim served for a stale ?v is still just a re-export of
// whatever runtime the host page actually loaded, never a mismatched second bundle.
// libBase (content-hashed, scripts/bundle-internal-libs.js) still serves bootstrap.
const libBase = `/lib/${internalLibsHash}`;
const runtimeShim = (file) => `/runtime/${file}?v=${runtimeShimsHash}`;
const importMap = `
  <script type="importmap" crossorigin="anonymous">
  {
    "imports": {
      "svelte": "${runtimeShim("svelte/index.js")}",
      "svelte/animate": "${runtimeShim("svelte/animate.js")}",
      "svelte/easing": "${runtimeShim("svelte/easing.js")}",
      "svelte/motion": "${runtimeShim("svelte/motion.js")}",
      "svelte/store": "${runtimeShim("svelte/store.js")}",
      "svelte/transition": "${runtimeShim("svelte/transition.js")}",
      "svelte/internal": "${runtimeShim("svelte/internal.js")}",
      "svelte/internal/client": "${runtimeShim("svelte/internal-client.js")}",
      "svelte/internal/disclose-version": "${runtimeShim("svelte/internal-disclose-version.js")}",
      "svelte/internal/flags/legacy": "${runtimeShim("svelte/internal-flags-legacy.js")}",
      "svelte/internal/flags/async": "${runtimeShim("svelte/internal-flags-async.js")}",
      "svelte/internal/flags/tracing": "${runtimeShim("svelte/internal-flags-tracing.js")}",
      "svelte/legacy": "${runtimeShim("svelte/legacy.js")}",
      "svelte/events": "${runtimeShim("svelte/events.js")}",
      "svelte/attachments": "${runtimeShim("svelte/attachments.js")}",
      "svelte/reactivity": "${runtimeShim("svelte/reactivity.js")}",
      "svelte/reactivity/window": "${runtimeShim("svelte/reactivity-window.js")}",
      "svelte-i18n": "${runtimeShim("svelte/i18n.js")}",
      "@panomc/sdk": "${runtimeShim("sdk/index.js")}",
      "@panomc/sdk/components/theme": "${runtimeShim("sdk/components-theme.js")}",
      "@panomc/sdk/components/panel": "${runtimeShim("sdk/components-panel.js")}",
      "@panomc/sdk/toasts": "${runtimeShim("sdk/toasts.js")}",
      "@panomc/sdk/utils/api": "${runtimeShim("sdk/utils-api.js")}",
      "@panomc/sdk/utils/auth": "${runtimeShim("sdk/utils-auth.js")}",
      "@panomc/sdk/utils/tooltip": "${runtimeShim("sdk/utils-tooltip.js")}",
      "@panomc/sdk/utils/language": "${runtimeShim("sdk/utils-language.js")}",
      "@panomc/sdk/utils/component": "${runtimeShim("sdk/utils-component.js")}",
      "@panomc/sdk/utils/text": "${runtimeShim("sdk/utils-text.js")}",
      "@panomc/sdk/variables": "${runtimeShim("sdk/variables.js")}",
      "@panomc/sdk/svelte": "${runtimeShim("sdk/svelte.js")}",
      "@panomc/sdk/internal": "${runtimeShim("sdk/internal.js")}"
    }
  }
  </script>
  <script defer src="${libBase}/bootstrap/bootstrap.bundle.min.js"></script>`;
const IMPORT_MAP_PLACEHOLDER = "%pano_lib_import%";
const IMPORT_MAP_PLACEHOLDER_LEN = IMPORT_MAP_PLACEHOLDER.length;

/** @type {import('@sveltejs/kit').Handle} */
export async function handle({
  event,
  event: {
    cookies,
    url: { pathname },
  },
  resolve,
}) {
  const locals = {};

  // noinspection JSUnresolvedReference
  const apiUrlEnv = process.env.API_URL;

  // noinspection JSUnresolvedReference
  const panoWebsiteUrlEnv = process.env.PANO_WEBSITE_URL;

  if (apiUrlEnv) {
    updateApiUrl(apiUrlEnv);
    locals.apiUrlEnv = apiUrlEnv;
  }

  if (panoWebsiteUrlEnv) {
    updatePanoWebsiteUrl(panoWebsiteUrlEnv);
    locals.panoWebsiteUrlEnv = panoWebsiteUrlEnv;
  }

  const jwt = getCookieWithHttpFallback(cookies, COOKIE_PREFIX + JWT_COOKIE_NAME);
  const csrfToken = getCookieWithHttpFallback(cookies, COOKIE_PREFIX + CSRF_TOKEN_COOKIE_NAME);

  locals.user =
    jwt && csrfToken &&
    !pathname.startsWith("/api/") &&
    !pathname.startsWith("/auth/") &&
    (await getCredentialsServerSide(jwt));

  locals.csrfToken = csrfToken;

  event.locals = locals;

  const response = await resolve(event, {
    transformPageChunk: ({ html }) => {
      const index = html.indexOf(IMPORT_MAP_PLACEHOLDER);
      if (index === -1) return html;
      return html.substring(0, index) + importMap + html.substring(index + IMPORT_MAP_PLACEHOLDER_LEN);
    },
  });

  const ct = response.headers.get("content-type") || "";
  if (ct.includes("text/html")) {
    const link = response.headers.get("link");
    if (link) {
      const filtered = stripModulePreload(link);
      if (filtered) response.headers.set("link", filtered);
      else response.headers.delete("link");
    }
  }

  return response;
}

/** @type {import('@sveltejs/kit').HandleServerError} */
export function handleError({ error, event }) {
  if (!shouldSuppressServerErrorLog(error)) {
    console.log("!!! [GLOBAL ERROR EVENT]:", event.url.href);
    console.error("!!! [GLOBAL ERROR CONTENT]:", error);
  }
  return {
    message: 'Internal Error',
    code: error?.code
  };
}

/** @type {import("@sveltejs/kit").HandleFetch} */
export async function handleFetch({ event, request, fetch }) {
  // Rewrite relative /api/ requests to the backend URL during SSR.
  // Load functions now use relative paths for consistent SSR↔CSR fetch dedup.
  if (request.url.startsWith(event.url.origin + "/api/")) {
    const apiPath = new URL(request.url).pathname + new URL(request.url).search;
    const backendUrl = API_URL.replace(/\/api\/?$/, "") + apiPath;
    request = new Request(backendUrl, request);
    request.headers.set("cookie", event.request.headers.get("cookie") || "");
    request.headers.set("Origin", API_URL);
  } else if (request.url.startsWith(API_URL)) {
    request.headers.set("cookie", event.request.headers.get("cookie") || "");
    request.headers.set("Origin", API_URL);
  }

  return fetch(request);
}