name: Release
on:
  push:
    branches: ["dev", "master"]
permissions:
  contents: read
jobs:
  release:
    uses: PanoMC/sdk/.github/workflows/theme-release.yml@dev
    with:
      theme-id: banana-theme
    secrets:
      TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
